const GET_DATA = 'GET_DATA'
const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
const GET_DATA_FAILURE = 'GET_DATA_FAILURE'
const GET_DATA_ASYNC = 'GET_DATA_ASYNC'

const types = {
  GET_DATA,
  GET_DATA_SUCCESS,
  GET_DATA_FAILURE,
  GET_DATA_ASYNC,
}

export default types
